#!/usr/bin/env sh

# Modified version of `fzopen' created by Anna Arad
# Available at: https://github.com/jarun/nnn/blob/master/plugins/fzopen

entry=$(fzf)

case "$(file -biL "$entry")" in
	*text*)
		"${VISUAL:-$EDITOR}" "$entry" ;;
	*)
		open "$entry" >/dev/null 2>&1 ;;
esac
